databases:
  - name: multimediadb
    plan: free
    databaseName: multimedia
    user: multimedia

services:
  - type: web
    plan: free
    name: multimedia
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn multimedia_app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: multimediadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4