databases:
  - name: multimedia_appdb
    plan: free
    databaseName: multimedia_app
    user: multimedia_app

services:
  - type: web
    plan: free
    name: multimedia_app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn multimedia_app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: multimedia_appdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4